CREATE DATABASE [QueryStoreDemo]
GO
ALTER DATABASE [QueryStoreDemo] SET AUTO_UPDATE_STATISTICS OFF 
GO
ALTER DATABASE [QueryStoreDemo] SET AUTO_CREATE_STATISTICS OFF 
GO
ALTER DATABASE [QueryStoreDemo] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [QueryStoreDemo] SET QUERY_STORE = OFF
GO