--Crating the resource pools
CREATE RESOURCE POOL ProductionPool
WITH
(
    MIN_CPU_PERCENT = 50,
    MAX_CPU_PERCENT = 100,
    MIN_MEMORY_PERCENT = 50,
    MAX_MEMORY_PERCENT = 100,
    AFFINITY SCHEDULER = AUTO
);

CREATE RESOURCE POOL SecondaryPool
WITH
(
    MIN_CPU_PERCENT = 0,
    MAX_CPU_PERCENT = 30,
    MIN_MEMORY_PERCENT = 0,
    MAX_MEMORY_PERCENT = 30,
    AFFINITY SCHEDULER = AUTO
);