-- Azure SQL Database
CREATE LOGIN [DP300User1] WITH PASSWORD = 'P@ssw0rd';

USE demo0616singledb;
GO
CREATE USER [DP300User1] FOR LOGIN [DP300User1];
GO
CREATE ROLE [SalesReader];
GO
ALTER ROLE [SalesReader] ADD MEMBER [DP300User1];
GO
GRANT SELECT, EXECUTE ON SCHEMA::SalesLT TO [SalesReader];
GO